// Generated by gencpp from file gcloud_speech_msgs/SpeechToTextActionGoal.msg
// DO NOT EDIT!


#ifndef GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTACTIONGOAL_H
#define GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <gcloud_speech_msgs/SpeechToTextGoal.h>

namespace gcloud_speech_msgs
{
template <class ContainerAllocator>
struct SpeechToTextActionGoal_
{
  typedef SpeechToTextActionGoal_<ContainerAllocator> Type;

  SpeechToTextActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  SpeechToTextActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::gcloud_speech_msgs::SpeechToTextGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechToTextActionGoal_

typedef ::gcloud_speech_msgs::SpeechToTextActionGoal_<std::allocator<void> > SpeechToTextActionGoal;

typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextActionGoal > SpeechToTextActionGoalPtr;
typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextActionGoal const> SpeechToTextActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gcloud_speech_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'gcloud_speech_msgs': ['/home/users/danbing/catkin_ws_fetch33/src/gcloud_speech_msgs/msg', '/home/users/danbing/catkin_ws_fetch33/devel/.private/gcloud_speech_msgs/share/gcloud_speech_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6175e2e8b986c5e017d26c349a3f49c4";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6175e2e8b986c5e0ULL;
  static const uint64_t static_value2 = 0x17d26c349a3f49c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gcloud_speech_msgs/SpeechToTextActionGoal";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
SpeechToTextGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: gcloud_speech_msgs/SpeechToTextGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Goal definition\n\
# Equivalent to google.cloud.speech.v1.StreamingRecognitionConfig. See also:\n\
# https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1#streamingrecognitionconfig\n\
\n\
# A list of strings containing words and phrases \"hints\" so that the speech\n\
# recognition is more likely to recognize them. This can be used to improve the\n\
# accuracy for specific words and phrases, for example, if specific commands are\n\
# typically spoken by the user. This can also be used to add additional words to\n\
# the vocabulary of the recognizer.\n\
string[] hints\n\
\n\
# Maximum number of recognition hypotheses to be returned. Specifically, the\n\
# maximum number of RecognitionHypothesis messages within each\n\
# SpeechToTextFeedback. The server may return fewer than max_alternatives. Valid\n\
# values are 0-30. A value of 0 or 1 will return a maximum of one. If omitted,\n\
# will return a maximum of one.\n\
int32 max_alternatives\n\
\n\
# Maximum listening duration. The recognizer will start listening immediately,\n\
# and will stop listening after \"listen_duration_sec\" seconds. If 0 or omitted,\n\
# will use an internal default value (14 seconds).\n\
int32 listen_duration_sec\n\
\n\
# Maximum recognition duration. The recognizer will start counting down\n\
# immediately, and after max_recognition_duration_sec seconds it will return no\n\
# matter whether there is a recognition result. If 0 or omitted, will use\n\
# a default value: listen_duration_sec + 2.\n\
int32 max_recognition_duration_sec\n\
\n\
\n\
# If false or omitted, interim results (tentative hypotheses) may be returned as\n\
# they become available (these interim results are indicated with the\n\
# is_portion_final=false flag). If true, only is_portion_final=true result(s)\n\
# are returned.\n\
bool suppress_interim_results\n\
";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechToTextActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gcloud_speech_msgs::SpeechToTextActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::gcloud_speech_msgs::SpeechToTextGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTACTIONGOAL_H
