// Generated by gencpp from file gcloud_speech_msgs/SpeechToTextFeedback.msg
// DO NOT EDIT!


#ifndef GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTFEEDBACK_H
#define GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gcloud_speech_msgs/RecognitionHypothesis.h>

namespace gcloud_speech_msgs
{
template <class ContainerAllocator>
struct SpeechToTextFeedback_
{
  typedef SpeechToTextFeedback_<ContainerAllocator> Type;

  SpeechToTextFeedback_()
    : hypotheses()
    , is_portion_final(false)
    , stability(0.0)  {
    }
  SpeechToTextFeedback_(const ContainerAllocator& _alloc)
    : hypotheses(_alloc)
    , is_portion_final(false)
    , stability(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::gcloud_speech_msgs::RecognitionHypothesis_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::gcloud_speech_msgs::RecognitionHypothesis_<ContainerAllocator> >::other >  _hypotheses_type;
  _hypotheses_type hypotheses;

   typedef uint8_t _is_portion_final_type;
  _is_portion_final_type is_portion_final;

   typedef double _stability_type;
  _stability_type stability;




  typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechToTextFeedback_

typedef ::gcloud_speech_msgs::SpeechToTextFeedback_<std::allocator<void> > SpeechToTextFeedback;

typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextFeedback > SpeechToTextFeedbackPtr;
typedef boost::shared_ptr< ::gcloud_speech_msgs::SpeechToTextFeedback const> SpeechToTextFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gcloud_speech_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'gcloud_speech_msgs': ['/home/users/danbing/catkin_workspace/src/gcloud_speech_msgs/msg', '/home/users/danbing/catkin_workspace/devel/.private/gcloud_speech_msgs/share/gcloud_speech_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d51422b863c8960964654dda15131a8";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d51422b863c8960ULL;
  static const uint64_t static_value2 = 0x964654dda15131a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gcloud_speech_msgs/SpeechToTextFeedback";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
\n\
# Feedback definition: users should mostly rely on these feedbacks to get\n\
# recognition results.\n\
# Equivalent to google.cloud.speech.v1.StreamingRecognitionResult. See also:\n\
# https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1#speechrecognitionresult\n\
\n\
# Transcript text representing the words that the user spoke. The length of this\n\
# array is equal to the following \"confidence\" array.\n\
gcloud_speech_msgs/RecognitionHypothesis[] hypotheses\n\
\n\
# If false, this SpeechToTextFeedback represents an interim result that may\n\
# change. If true, the recognizer will not return any further hypotheses for\n\
# this portion of the transcript and corresponding audio as\n\
# SpeechToTextFeedback.\n\
bool is_portion_final\n\
\n\
# An estimate of the likelihood that the recognizer will not change its guess\n\
# about this interim result. Values range from 0.0 (completely unstable) to\n\
# 1.0 (completely stable). This field is only provided for interim results\n\
# (is_portion_final=false). The default of 0.0 is a sentinel value indicating\n\
# stability was not set.\n\
float64 stability\n\
\n\
\n\
================================================================================\n\
MSG: gcloud_speech_msgs/RecognitionHypothesis\n\
# Recognition hypothesis for a portion of speech. Equivalent to\n\
# google.cloud.speech.v1.SpeechRecognitionAlternative, See also:\n\
# https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1#speechrecognitionalternative\n\
\n\
# Transcript text representing the words that the user spoke.\n\
string transcript\n\
\n\
# The confidence estimate between 0.0 and 1.0. A higher number indicates an\n\
# estimated greater likelihood that the recognized words are correct. This field\n\
# is typically provided only for the top hypothesis, and only for\n\
# is_portion_final=true results. Clients should not rely on the confidence field\n\
# as it is not guaranteed to be accurate or consistent. The default of 0.0 is a\n\
# sentinel value indicating confidence was not set.\n\
float64 confidence\n\
";
  }

  static const char* value(const ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hypotheses);
      stream.next(m.is_portion_final);
      stream.next(m.stability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechToTextFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gcloud_speech_msgs::SpeechToTextFeedback_<ContainerAllocator>& v)
  {
    s << indent << "hypotheses[]" << std::endl;
    for (size_t i = 0; i < v.hypotheses.size(); ++i)
    {
      s << indent << "  hypotheses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gcloud_speech_msgs::RecognitionHypothesis_<ContainerAllocator> >::stream(s, indent + "    ", v.hypotheses[i]);
    }
    s << indent << "is_portion_final: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_portion_final);
    s << indent << "stability: ";
    Printer<double>::stream(s, indent + "  ", v.stability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GCLOUD_SPEECH_MSGS_MESSAGE_SPEECHTOTEXTFEEDBACK_H
