// Generated by gencpp from file acoustic_magic_msgs/SoundSourceAngle.msg
// DO NOT EDIT!


#ifndef ACOUSTIC_MAGIC_MSGS_MESSAGE_SOUNDSOURCEANGLE_H
#define ACOUSTIC_MAGIC_MSGS_MESSAGE_SOUNDSOURCEANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace acoustic_magic_msgs
{
template <class ContainerAllocator>
struct SoundSourceAngle_
{
  typedef SoundSourceAngle_<ContainerAllocator> Type;

  SoundSourceAngle_()
    : header()
    , is_valid(false)
    , angle(0.0)  {
    }
  SoundSourceAngle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_valid(false)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef double _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> const> ConstPtr;

}; // struct SoundSourceAngle_

typedef ::acoustic_magic_msgs::SoundSourceAngle_<std::allocator<void> > SoundSourceAngle;

typedef boost::shared_ptr< ::acoustic_magic_msgs::SoundSourceAngle > SoundSourceAnglePtr;
typedef boost::shared_ptr< ::acoustic_magic_msgs::SoundSourceAngle const> SoundSourceAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace acoustic_magic_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'acoustic_magic_msgs': ['/home/users/danbing/catkin_ws_fetch33/src/acoustic_magic_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73d22af5de75b14e00863995e84490c5";
  }

  static const char* value(const ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73d22af5de75b14eULL;
  static const uint64_t static_value2 = 0x00863995e84490c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acoustic_magic_msgs/SoundSourceAngle";
  }

  static const char* value(const ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool is_valid\n\
float64 angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_valid);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundSourceAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acoustic_magic_msgs::SoundSourceAngle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACOUSTIC_MAGIC_MSGS_MESSAGE_SOUNDSOURCEANGLE_H
