(cl:defpackage gcloud_speech_msgs-msg
  (:use )
  (:export
   "<RECOGNITIONHYPOTHESIS>"
   "RECOGNITIONHYPOTHESIS"
   "<LINEARPCM16LE16000AUDIO>"
   "LINEARPCM16LE16000AUDIO"
   "<SPEECHTOTEXTRESULT>"
   "SPEECHTOTEXTRESULT"
   "<SPEECHTOTEXTGOAL>"
   "SPEECHTOTEXTGOAL"
   "<SPEECHTOTEXTFEEDBACK>"
   "SPEECHTOTEXTFEEDBACK"
   "<SPEECHTOTEXTACTIONRESULT>"
   "SPEECHTOTEXTACTIONRESULT"
   "<SPEECHTOTEXTACTIONGOAL>"
   "SPEECHTOTEXTACTIONGOAL"
   "<SPEECHTOTEXTACTION>"
   "SPEECHTOTEXTACTION"
   "<SPEECHTOTEXTACTIONFEEDBACK>"
   "SPEECHTOTEXTACTIONFEEDBACK"
  ))

